### ISSUE TITLE
Code crashes

### ISSUE THREAD

**Issue by kechua** [IljaManakov/HDcycleGAN#4]
Hello! I've tried to run the code on your data, but encountered several problems

1) In my case it turned out that some type conversion is needed in criterion.py (targets, returned by discriminator_loss function, lines 122-125, to be converted to long, otherwise an error is thrown)

2) When fixed 1), I encountered 'CUDA out of memory' on the forward pass of the very first iteration. GPU I use has 6 GB total capacity. In the paper you describe running inference on 2GB GTX 1050, so it's unclear what might have gone wrong.

I was able to temporarily fix 2) by decreasing batch size from 4 to 1.

3) When loss calculation is executed, training crashes with RuntimeError: multi-target not supported at /tmp/pip-req-build-ufslq_a9/aten/src/THCUNN/generic/ClassNLLCriterion.cu:15. I have traced this error and realised that it goes up to the arguments of the cross-entropy loss. It turns out that the function expects labels in form of a vector, but gets a matrix of one-hot-encoded labels

Can you please help me with these errors?

**Comment by IljaManakov** [comment]
Hi, I cannot reproduce your error. I have just created a new folder and cloned this repo from git. Both train.py and train_without_trainer.py worked after I ran download_dataset.py. Are you running this code with custom data? If so, you have to make sure, that the data pipeline you are using provides a vector of class labels instead of one-hot labels. See the official PyTorch documentation at https://pytorch.org/docs/stable/nn.html#torch.nn.CrossEntropyLoss

Regarding GPU memory, you have to distinguish inference from training. While I ran inference on my Laptop using the built-in 1050, I trained the models on a GTX 1080ti, which has 11GB VRAM.

Cheers,
Ilja

**Comment by kechua** [comment]
Thank you for the answer!

As for GPU, seems like I lack resources, you are right. 

As for the crash: I've just run all the necessary commands on Google Colab and still get the type error (i.e. the one described above). Pretty sure that should I fix it, I would get the loss error.  What I do is
1. copy your repository to google drive, change parent_folder in config.py
2. Run the following comands 
!cp -r ./drive/My\ Drive/HDcycleGANpure/* ./
!python download_dataset.py
!python train_without_trainer.py -c config.py

I do run the code on your data

Best,
Ivan

**Comment by zaaabik** [comment]
If I understood correctly, the problem might come from the version of PyTorch.
Can you please share your version of PyTorch?

I can reproduce the error with casting to long if PyTorch version == 1.5.0 if I downgrade to 0.4.0 then everything is all right. 

Probably, you can set certainly version in requirements.txt.

Best,
Artem.

**Comment by lelikchern** [comment]
Hi all,
ClassificationLoss and ClassificationLossHD both return several values (it's interesting, since in the previous commits they used to return solitary entities, namely the sum of the several losses that make up the loss we need) . But in training_without_trainer, the loss is saved into one variable, not a tuple:
loss = criterion(result, ([i.float() for i in images], labels))
This gives rise to errors when calling
optimizer.backward(loss)

So a way of going around (my guess) is either:
1. Make the call in ClassificationLoss return one value (as before).
2. Do something like (loss1, loss2, loss3) = criterion(...) in training_without_trainer
3. Change the insides of optimizer, which I think you just did yesterday, am I right?

**Comment by IljaManakov** [comment]
@lelikchern that is correct. It was a bug I introduced when rewriting the code for this public repository. the generator and discriminator weights need to be updated independently. I fixed this some time back for train.py by introducing the OptimizerCollection class. I had however not fixed it in train_without_trainer.py, which I noticed and remedied yesterday. But I am not sure that this is the source of the error described by @kechua.

@kechua:
Can you check, whether the labels you get from the dataloader are indeed of shape (batch_size,)?
As you have already figured out, CrossEntropyLoss does not accept multi-label targets (you would need BCELoss for that). 
Also, since you don't mention it in your code sample: you have to correctly set the path to the dataset in config.py.

**Comment by kechua** [comment]
Hello, Ilja!

Labels I got from the loader are of the format [tensor([1, 1, 1, 1]), tensor([2, 2, 2, 2])] (in this particular case, batch_size=4). Your loader yields the same.

Actually, I've changed the code in several places and now it works for me. 

1) I've made type conversion in criterion.py (targets, returned by discriminator_loss function, lines 122-125, to be converted to long, otherwise an error is thrown in my case)

2) In criterion.py changed the function generate_fake_targets. Made generated targets not one-hot-encoded vectors, but scalars, e.g. ln_t = pt.tensor([[0, 0, 1]]*batch_size).to(template) => ln_t = pt.tensor([2]*batch_size).to(template)

3) After fix 2) I stumbled accross the error with tuples, which you fixed :)

4) After 3) some strange error occured (one of the variables needed for gradient computation has been modified by an inplace operation...). Somehow it disappeared after I had downgraded to torch 1.0.0

5) In train_withoit trainer I deleted the lines i) optimizer.zero_grad() ii) optimizer.step(), because they would throw an error. As I understand, you have incorporated zero_grad and step into the backward method of the oprimizer.

6) On the inference stage I've used your code from measurements.py and in the class CyGAN, line 130 I had to substitute 'generator_hq' with 'generator_ln'; otherwiseI would get an empty dictionary.

After these changes your GAN have started training on my data and after 10 iterations I've obtained something like denoising, very blured though :)
